version: '3.9'

services:
  csharpapp:
    container_name: spst-kniznica-container
    image: spst-kniznica-image
    build: .
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=spstkniznicabackend;Username=postgres;Password=PETERdinis1234"
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}